// Usamos una variable genérica. La lógica en index.html se encargará de leerla
// y eliminarla inmediatamente después de su uso para prevenir bugs.
window.currentGameListString = `
-Battletoads in Battlemaniacs (USA) "https://www.mediafire.com/file/1ujmxizlcif3kny/Battletoads+in+Battlemaniacs+%28USA%29.sfc"
-Battletoads-Double Dragon (USA) "https://www.mediafire.com/file/2g7keyoxf2mwkcp/Battletoads-Double+Dragon+%28USA%29.sfc"
-Clay Fighter (USA) "https://www.mediafire.com/file/oomb7dq1u7xp5ga/Clay+Fighter+%28USA%29.sfc"
-Clay Fighter 2 - Judgment Clay (USA) "https://www.mediafire.com/file/7bdllbb9ov95wnw/Clay+Fighter+2+-+Judgment+Clay+%28USA%29.sfc"
-Demon's Crest (USA) "https://www.mediafire.com/file/bpo91miqjhiec09/Demon%27s+Crest+%28USA%29.sfc"
-Dirt Trax FX (USA) "https://www.mediafire.com/file/0nt3j9sazfuci0g/Dirt+Trax+FX+%28USA%29.sfc"
-Donkey Kong Country (USA) (Rev 2) "https://www.mediafire.com/file/jqw347eiwiinr4a/Donkey+Kong+Country+%28USA%29+%28Rev+2%29.sfc"
-Dragon Ball Z - Hyper Dimension (tr) "https://www.mediafire.com/file/eq64wu1rl2nfxxb/Dragon+Ball+Z+-+Hyper+Dimension+%28tr%29.sfc"
-Dragon Ball Z - Super Butouden (tr) "https://www.mediafire.com/file/jgab4zxsiuds2rr/Dragon+Ball+Z+-+Super+Butouden+%28tr%29.sfc"
-Killer Instinct (USA) (Rev 1) "https://www.mediafire.com/file/kv8iw84dnlmfcfs/Killer+Instinct+%28USA%29+%28Rev+1%29.sfc"
-Kirby Super Star (USA) "https://www.mediafire.com/file/vatvwq8tr4fwnh9/Kirby+Super+Star+%28USA%29.sfc"
-Mortal Kombat (USA) (Rev 1) "https://www.mediafire.com/file/gw1zqghwclddzhu/Mortal+Kombat+%28USA%29+%28Rev+1%29.sfc"
-Mortal Kombat 3 (USA) "https://www.mediafire.com/file/ezud92s33autrm4/Mortal+Kombat+3+%28USA%29.sfc"
-Mortal Kombat II (USA) (Rev 1) "https://www.mediafire.com/file/9rf3cve6w2rxjig/Mortal+Kombat+II+%28USA%29+%28Rev+1%29.sfc"
-Ninja Gaiden Trilogy (USA) "https://www.mediafire.com/file/1vzqi64y6ea5wot/Ninja+Gaiden+Trilogy+%28USA%29.sfc"
-Primal Rage (USA) "https://www.mediafire.com/file/4dzbrahux4azcox/Primal+Rage+%28USA%29.sfc"
-Star Fox (USA) (Rev 2) "https://www.mediafire.com/file/ekbs8p48vtfhp7f/Star+Fox+%28USA%29+%28Rev+2%29.sfc"
-Star Fox 2 (USA, Europe) (Classic Mini, Switch Online) "https://www.mediafire.com/file/zr3t9eyk23vk1m0/Star+Fox+2+%28USA%2C+Europe%29+%28Classic+Mini%2C+Switch+Online%29.sfc"
-Super Castlevania IV (USA) "https://www.mediafire.com/file/lxkq0l0wc5py0n7/Super+Castlevania+IV+%28USA%29.sfc"
-Super Mario All-Stars (USA, Europe) (Switch Online) "https://www.mediafire.com/file/pkz7uxzsyihgqmd/Super+Mario+All-Stars+%28USA%2C+Europe%29+%28Switch+Online%29.sfc"
-Super Mario World (USA, Europe) (Virtual Console, Classic Mini, Switch Online) "https://www.mediafire.com/file/26lha770a284n7j/Super+Mario+World+%28USA%2C+Europe%29+%28Virtual+Console%2C+Classic+Mini%2C+Switch+Online%29.sfc"
-Super Metroid (USA, Europe) (En,Ja) (Virtual Console, Classic Mini, Switch Online) "https://www.mediafire.com/file/udnqbyms533oz3q/Super+Metroid+%28USA%2C+Europe%29+%28En%2CJa%29+%28Virtual+Console%2C+Classic+Mini%2C+Switch+Online%29.sfc"
-Super Probotector - Alien Rebels (World) (Contra Anniversary Collection) "https://www.mediafire.com/file/m78875lkdnocpnz/Super+Probotector+-+Alien+Rebels+%28World%29+%28Contra+Anniversary+Collection%29.sfc"
-Super Smash T.V. (USA) "https://www.mediafire.com/file/eoqkm9nfjgmc7c6/Super+Smash+T.V.+%28USA%29.sfc"
-Super Street Fighter II (USA) (Rev 1) "https://www.mediafire.com/file/o0keqzghhpqqdkb/Super+Street+Fighter+II+%28USA%29+%28Rev+1%29.sfc"
-Teenage Mutant Ninja Turtles IV - Turtles in Time (USA) "https://www.mediafire.com/file/nzz4by0gzqxqx46/Teenage+Mutant+Ninja+Turtles+IV+-+Turtles+in+Time+%28USA%29.sfc"
-Ultimate Mortal Kombat 3 (USA) "https://www.mediafire.com/file/fwg27jupt9y8c48/Ultimate+Mortal+Kombat+3+%28USA%29.sfc"
`;